### ISSUE TITLE
Empty line characters move

### ISSUE THREAD

**Issue by maddymakesgames** [cowboy8625/ReVim#16]
If you move the cursor up after putting in multiple lines the ~ will move up with the cursor.
Are we somehow basing the ~ off the cursor? That doesn't make sense but possibly?
![moving tildea](https://user-images.githubusercontent.com/16091033/73610677-0e012600-45a8-11ea-9e36-dfa21a80b0af.gif)

**Comment by cowboy8625** [comment]
I cant remake this bug.

**Comment by cowboy8625** [comment]
This is no longer a bug do to restarting the project.
