### ISSUE TITLE
Move Curser out side of text

### ISSUE THREAD

**Issue by cowboy8625** [cowboy8625/ReVim#9]
With or without text Curser can move any where on screen and that can cause a crash upon entering into insert mode.

**Comment by cowboy8625** [comment]
Now after adding text to screen or opening up a file you can move around the file and add text as needed BUT if your curser goes out side of text feild when entering insert mode upon the first key pressed the program with crash.

**Comment by maddymakesgames** [comment]
This probably can get fixed by checking the textbuffer to see if the cursor is within the text, like probably check the number of lines to see if you can move the cursor down and check the length of the current line to see if the cursor can be moved horizontally.

**Comment by cowboy8625** [comment]
Issuse Fix.
